### ISSUE TITLE
Platform not found: sensor.google_keep

### ISSUE THREAD

**Issue by LbDab** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#1]
HassOS 0.96.5
Configuration check result: Platform not found: sensor.google_keep

configuration.yaml:
```
  - platform: google_keep
    username: username
    password: password
```

Running `pip install gkeepapi` in HAssOS terminal returns `command not found`

**Comment by PiotrMachowski** [comment]
Have you performed full restart of HA? Is there anything more in logs?

**Comment by LbDab** [comment]
It is working after 2 restarts: install from HACS, restart, change config.yaml restart.

**Comment by AaronArgent** [comment]
I still get this when doing check config

**Comment by PiotrMachowski** [comment]
Could you provide more details? Do you have the latest version? Which version of HA do you have? Have you performed a restart?
