### ISSUE TITLE
 GitHub returned 502 (rate_limit) 

### ISSUE THREAD

**Issue by austwhite** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#10]
I just updated the Google Keep component using HACS and I get the following error:

Log Details (ERROR)
Logger: hacs.factory
Source: custom_components/hacs/hacsbase/task_factory.py:62
First occurred: 5:01:01 AM (1 occurrences)
Last logged: 5:01:01 AM

PiotrMachowski/Home-Assistant-custom-components-Google-Keep - GitHub returned 502 for https://api.github.com/rate_limit

**Comment by PiotrMachowski** [comment]
This is not a problem with this component, but with HACS
