### ISSUE TITLE
Can't get this to work any longer

### ISSUE THREAD

**Issue by fribse** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#14]
It looks to me like Google has (again) changed something, the provided link does not give me a way to create an app password.
Do I need enable access to lower security apps?

**Comment by PiotrMachowski** [comment]
What exactly problem do you have? Is there anything in logs?

**Comment by fribse** [comment]
I think I figured it out in the meantime, to have app passwords, you need to have two factor authentication. I had disabled that as it kept popping up on my android tv's, I've now renabled that, so I'm trying to set it up now,

**Comment by PiotrMachowski** [comment]
If you don't use 2FA you should it should work with a normal password

**Comment by fribse** [comment]
Ok, I just added 2FA again, and it works again with the app password, but good to know.
I'll see what happens on the TV's, if they go borked again, I'll turn off 2FA, and set the normal pw for the keep sensor, thanks for getting back to me! Love the sensor :-)

**Comment by PiotrMachowski** [comment]
No problem, happy to help :)
