### ISSUE TITLE
Integration 'google_keep' not found.

### ISSUE THREAD

**Issue by jokerigno** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#18]
After update to 2021.06 integration is not working anymore.

Can you please update it?

This is the message in HA blog:

Custom integrations (custom_components)

As mentioned in every release since 2021.3, custom integrations will require a version key in their manifest file.

As of this release, if that version key is missing in the manifest, the custom integration will no longer be loaded.

**Comment by PiotrMachowski** [comment]
This integration already has version [link](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Google-Keep/blob/master/custom_components/google_keep/manifest.json), please make sure that you have this version installed

**Comment by jokerigno** [comment]
Sorry. You're right! I do update my version.
