### ISSUE TITLE
Warning in LOG

### ISSUE THREAD

**Issue by jokerigno** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#25]
Just found this message in my log:

Entity sensor.google_keep_c1042c5575 (<class 'custom_components.google_keep.sensor.GoogleKeepSensor'>) implements device_state_attributes. Please report it to the custom component author.
My understanding is that device_state_attributes has been deprecated and replaced with extra_state_attributes.

Thank you

**Comment by BebeMischa** [comment]
This has been fixed a week ago, do you use the last version?

**Comment by jokerigno** [comment]
Solved
