### ISSUE TITLE
not findable in hacs

### ISSUE THREAD

**Issue by IIIdefconIII** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#35]
Hi i dont find it in hacs, did i missed something?

![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Google-Keep/assets/9917659/4d7c9422-7aa9-461a-abff-fdbb7b8c0062)

**Comment by PiotrMachowski** [comment]
It has been removed from HACS because it has been broken for a quite some time :(

**Comment by IIIdefconIII** [comment]
Ah that's a bummer,  ill try to fix or maybe you know a well replacement app that workd on phone windows homeassitant and perhaps the ghub
