### ISSUE TITLE
Add App password instructions

### ISSUE THREAD

**Issue by gregcsw** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#4]
Hi

Could I suggest adding instructions to the documentation for how to get the App Password.

From https://github.com/klejejs/ha_keep_notes_sensor

> To get Google account password, go to https://myaccount.google.com/apppasswords. For Select app choose other and when you are asked for name, write anything. Then copy your password and use it in password: field.

Keep in mind that you will be able to see your created password only once.

Thanks Greg

**Comment by PiotrMachowski** [comment]
I have updated documentation with suggested information
