### ISSUE TITLE
Platform error sensor.google_keep

### ISSUE THREAD

**Issue by kernehed** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#6]
Hi,

I get this error when trying to set up Google Keep Sensor on Hassio:
`Platform error sensor.google_keep - No module named 'gpsoauth'`

**Home Assistant
0.100.3**

Any idea why?

**Comment by PiotrMachowski** [comment]
`gpsoauth` is a library used by library this integration uses to get data from Google Keep. It seems like there were some problems during installation, as all dependencies should be downloaded automatically. I suggest to remove this custom component, restart HA, install it again and restart HA second time.

**Comment by kernehed** [comment]
I got the same problem unfortunately. More ideas?

**Comment by kernehed** [comment]
I managed to fix this using the `Custom deps deployment` Add-on.
With this configuration:

```
{
  "pypi": [
    "gpsoauth"
  ],
  "apk": []
}

```

Now it's installed and working. Thank you!

**Comment by PiotrMachowski** [comment]
You probably also could modify `manifest.json` and add `gpsoauth` to requirements:

```
{
  "domain": "google_keep",
  "name": "Google Keep",
  "documentation": "https://github.com/PiotrMachowski/Home-Assistant-custom-components-Google-Keep",
  "dependencies": [],
  "codeowners": ["PiotrMachowski"],
  "requirements": ["gkeepapi", "gpsoauth"]
}
```
