### ISSUE TITLE
example use cases

### ISSUE THREAD

**Issue by fantapop** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#8]
Hey there, interesting project you have here!  I use google keep myself.  I'm trying to imagine good use cases for this integration.  What do you use it for?  Do you have any other ideas?  thanks.

**Comment by PiotrMachowski** [comment]
Hi, I use it for sharing TODO notes and shopping list. It is displayed on a dashboard, so you can check everything without taking your phone out.
